// <auto-generated />
namespace p00.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TopicEVTOdocumnt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TopicEVTOdocumnt));
        
        string IMigrationMetadata.Id
        {
            get { return "202006241600224_TopicEVTOdocumnt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
